### ISSUE TITLE
Incremental/arbitrary parsing

### ISSUE THREAD

**Issue by onthegit** [steinwurf/petro#49]
Hello,
thanks for the library. Can the library do Incremental/arbitrary parsing? E.g given bytes from MP4  file to try to parse the moov? And once moov is parsed based on the sample offset to be able to parse that sample (chunk)?

**Comment by jpihl** [comment]
Hello, I haven't worked on this library in a long time.

But I think it should be possible to do what you want.
Have you had a look at the examples?
